Fix search results not displaying & add backdrop-filter to several elements
DiscordStyles/FrostedGlass pull request #107
Opened 2024-11-01 22:26 UTC by RickyC0626

- **Search results** - applied `mask-image` manually to display results and hide overflow behind gradient

| Before | After |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/28534874-3919-4aab-8996-5e4b3adc45bb) | ![image](https://github.com/user-attachments/assets/525ad90d-f449-4d75-bc60-e31182c35ff6) | 

- **"Jump to Present" bar** - added backdrop filter to not see overlapping background text

| Before | After |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/d335474d-c774-4928-930b-6bc719bb59d6) | ![image](https://github.com/user-attachments/assets/cf4b18c9-024e-47f2-864f-f37fc4ee541c) | 

- **Hover reaction bar** - added backdrop filter to not see overlapping background text

| Before | After |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/f10f24fc-171b-4b6b-9267-618a1ef597c8) | ![image](https://github.com/user-attachments/assets/c7541207-13ff-4049-8e02-ce83bb6ad317) | 

- Updated default background image for smoother color palette

![image](https://wallpapercave.com/wp/wp6248666.jpg)

2024-11-04 03:01 UTC, Gibbu requested changes

2024-11-04 03:01 UTC, Gibbu commented on package-lock.json
I highly... HIGHLY suggest switch from the regular `npm` to [pnpm](https://pnpm.io). It's faster and uses less disk space.

If not, please delete this file. It is not required in the PR.

2024-11-04 15:36 UTC, RickyC0626 commented on package-lock.json
Will do

2024-11-07 10:00 UTC, Gibbu approved these changes

2024-11-07 10:00 UTC, merged